name: Wrap and Release
on: [push]
jobs:
  wrap-and-release:
    runs-on: ubuntu-latest
    container: duorbitalhud/duwrap:latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - run: cd scripts && ./wrap.sh false

