name: Wrap and Release
on: [push]
jobs:
  wrap-and-release:
    runs-on: ubuntu-latest
    container: duorbitalhud/duwrap:latest
    steps:
      - uses: actions/checkout@v2

      - run: ls -la # debug

      - name: Wrap
        run: |
          ./scripts/wrap.sh true
          echo "VERSION_NUMBER=$( cat ButtonHUD.conf.version )" >> $GITHUB_ENV

      - name: Create Release Notes
        run: ./scripts/latest-changes.sh > ReleaseNotes.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NUMBER }}
          release_name: Release v${{ env.VERSION_NUMBER }}
          body_path: ReleaseNotes.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above
          asset_path: ./ButtonHUD.conf
          asset_name: ButtonHUD.conf
          asset_content_type: text/yaml
